<a href="https://colab.research.google.com/github/ElviraKonovalov/soen471-bigData/blob/main/features_18_27_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [28]:
file = 'Motor Vehicle Collisions with KSI Data.csv'
df=  pd.read_csv(file, sep=',');

columns_to_drop = ['_id', 'ACCNUM', 'TIME', 'OFFSET', 'WARDNUM', 'DIVISION', 'ACCLOC', 'FATAL_NO', 'PEDTYPE', 'PEDACT', 'PEDCOND', 'CYCLISTYPE', 'CYCACT', 'CYCCOND', 'POLICE_DIVISION', 'ObjectId', 'geometry']
df = df.drop(columns=columns_to_drop)

df = df.iloc[:, 18:27]
df

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,LIGHT,LOCCOORD,MANOEUVER,MOTORCYCLE,NEIGHBOURHOOD,PASSENGER,PEDESTRIAN,RDSFCOND,REDLIGHT
0,Daylight,Intersection,Turning Left,NaN,High Park North (88),NaN,Yes,Dry,NaN
1,Daylight,Intersection,NaN,NaN,High Park North (88),NaN,Yes,Dry,NaN
2,Daylight,Intersection,Turning Right,Yes,Rouge (131),NaN,NaN,Dry,Yes
3,Daylight,Intersection,Going Ahead,Yes,Rouge (131),NaN,NaN,Dry,Yes
4,Dark,Mid-Block,Going Ahead,NaN,Eglinton East (138),NaN,Yes,Dry,NaN
...,...,...,...,...,...,...,...,...,...
16855,Daylight,Mid-Block,Going Ahead,NaN,Cliffcrest (123),NaN,NaN,Dry,NaN
16856,Daylight,Intersection,Turning Left,NaN,Eglinton East (138),Yes,NaN,Dry,NaN
16857,Daylight,Intersection,Going Ahead,NaN,Eglinton East (138),Yes,NaN,Dry,NaN
16858,Daylight,Intersection,NaN,NaN,Eglinton East (138),Yes,NaN,Dry,NaN
16859,Daylight,Mid-Block,Slowing or Stopping,NaN,Dovercourt-Wallace Emerson-Junction (93),NaN,NaN,Dry,NaN

In [29]:

"""
LIGHT - keep - dictates to some degree the visibility that the driver had
LOCCOORD - keep - intersection are usually busier than mid-block
MANOEUVER - keep - turning left and right has dead spots that the driver might've missed
MOTORCYCLE - keep? - usually move at higher speed and are smaller than a car, therefore harder to notice
NEIGHBOURDHOOD - discard - there's already HOOD_ID
PASSENGER - keep - passenger can be a distraction for the driver
PEDESTRIAN - keep? - can have unpredictable movement, more than a vehicule
RDSFCOND - keep - dry condition result to shorter breaking distance, which can help avoid certain collisions
REDLIGHT - keep? - if a driver burns a red light theres high probability of having an accident
"""

columns_to_drop = ['NEIGHBOURHOOD']
df = df.drop(columns=columns_to_drop)

df

,LIGHT,LOCCOORD,MANOEUVER,MOTORCYCLE,PASSENGER,PEDESTRIAN,RDSFCOND,REDLIGHT
0,Daylight,Intersection,Turning Left,NaN,NaN,Yes,Dry,NaN
1,Daylight,Intersection,NaN,NaN,NaN,Yes,Dry,NaN
2,Daylight,Intersection,Turning Right,Yes,NaN,NaN,Dry,Yes
3,Daylight,Intersection,Going Ahead,Yes,NaN,NaN,Dry,Yes
4,Dark,Mid-Block,Going Ahead,NaN,NaN,Yes,Dry,NaN
...,...,...,...,...,...,...,...,...
16855,Daylight,Mid-Block,Going Ahead,NaN,NaN,NaN,Dry,NaN
16856,Daylight,Intersection,Turning Left,NaN,Yes,NaN,Dry,NaN
16857,Daylight,Intersection,Going Ahead,NaN,Yes,NaN,Dry,NaN
16858,Daylight,Intersection,NaN,NaN,Yes,NaN,Dry,NaN
16859,Daylight,Mid-Block,Slowing or Stopping,NaN,NaN,NaN,Dry,NaN

In [30]:
#LIGHT
df.LIGHT.unique()

# Dropping all rows that have "Other" as value

df = df.drop(df[df.LIGHT == 'Other'].index)

df = df.drop(df[df.LIGHT.isnull()].index)
df.LIGHT.unique()

array(['Daylight', 'Dark', 'Dawn, artificial', 'Dusk, artificial', 'Dusk',
       'Dark, artificial', 'Dawn', 'Daylight, artificial'], dtype=object)

In [31]:
#LOCCOORD
df.LOCCOORD.unique()
df.LOCCOORD.isnull().sum() #105

105

In [32]:
#PEDESTRIAN
#replace every "NaN" to False and "Yes" to True

df.PEDESTRIAN.unique()
df['PEDESTRIAN'] = df['PEDESTRIAN'].replace('Yes',True)
df['PEDESTRIAN'] = df['PEDESTRIAN'].fillna(False)

In [33]:
#PASSENGER
#replace every "NaN" to False and "Yes" to True

df.PASSENGER.unique()
df['PASSENGER'] = df['PASSENGER'].replace('Yes',True)
df['PASSENGER'] = df['PASSENGER'].fillna(False)

In [34]:
#MOTORCYCLE
#replace every "NaN" to False and "Yes" to True

df.MOTORCYCLE.unique()
df['MOTORCYCLE'] = df['MOTORCYCLE'].replace('Yes',True)
df['MOTORCYCLE'] = df['MOTORCYCLE'].fillna(False)

In [35]:
df.RDSFCOND.unique()
df.RDSFCOND.isnull().sum() # 23

21

In [36]:
#REDLIGHT
#replace every "NaN" to False and "Yes" to True

df.REDLIGHT.unique()
df['REDLIGHT'] = df3['REDLIGHT'].replace('Yes',True)
df['REDLIGHT'] = df3['REDLIGHT'].fillna(False)